### PR TITLE
Add nested syntax highlighting for comment-directed template literals

### PR DESCRIPTION
**Pull request by blake-regalia**
A common use of mutli-line template literals is to embed snippets of code, whether it be HTML/CSS in the browser, or SQL in node.js.

With this PR, users can enable nested syntax highlighting on their long template literals to make embedded snippets easier to read. This is done by using a block comment directive. The complete syntax for the directive is as follows:

```
/* syntax: {SYNTAX_NAME} */ tag? `contents`
```

Where the `tag` identifier may appear before or after the syntax block comment directive.

### Commenting:
With nested highlighting, commenting works as one would expect (this is automatic w/ Sublime).

ecmascript-syntax-commenting mov

### Interpolation:
Scopes are properly maintained for interpolated expressions.

ecmascript-syntax-sql mov

### Nested template literals
You can even enable nested highlighting on template literals within interpolated expressions, in case, you know, should you need to... 😉

ecmascript-syntax-css mov

### CODE REVIEW

**Comment by blake-regalia** [comment]
@bathos This introduces several new scopes:
- `meta.interpolation.syntax`
- `meta.interpolation.syntax.sql`
- `meta.interpolation.syntax.html`
- `meta.interpolation.syntax.css`
- `meta.interpolation.syntax.js`

I copied the style from `meta.interpolation.jsx` onto `meta.interpolation.syntax` in excelsior -- but you may wish to style this differently.

**Comment by bathos** [comment]
whoa! I recently added detection of template literals as css for `<style jsx>` because it seemed sufficiently unlikely to be a false signal, but had never done anything similar before that (for e.g. html detection) because of the danger of false positives. This is a brilliant solution, I love it!

**Comment by bathos** [comment]
This looks good to me (and thanks for including the explanatory comments). I think this deserves description in the readme and the write up here w/ its images could be used for that. If you want to add that, feed free; if not let me know and I’ll merge / do the write up.

**Comment by blake-regalia** [comment]
Gladly!

**Pull request merged**
