### PR TITLE
‘Spring 2019 Update’ (i.e. random crap)

### PR DESCRIPTION
**Pull request by bathos**
This includes a number of updates I’ve been meaning to push for a while, but I’m unsure how to get the build stuff working and I assume that needs to be run before this can be committed to master (the command given in the build readme does not seem to do anything, at least on windows).

1. Decorators update

When we originally implemented the decorators grammar, it was not yet mature and had ambiguity issues that forced us to just kinda fudge it. This is no longer true, the grammar in the current spec is well-formed and can be handled properly. I introduced some new scopes to go with this, in particular one which gets a background in the excelsior theme to make parenthesized decorators clearly distinct from decorator call expression args:

image

2. Also seen in that pic is private methods, inclusive of static / async / async gen / gen / accessor methods. I tweaked the excelsior color for that after the shot though to something more washed out to reduce the color collisions with the prefixes / help keep these ‘implementation detail’ methods less prominent from their public API peers. still ugly, eh.

3. I’ve added handling of template tags named exactly 'css' or 'html' when no directive comment is present. In the former case, it uses the custom CSS rules rather than deferring to sublime css, which has more issues with interpolation & a brace matching bug with nested vars that drives me insane (shown not happening in the screenie above). For HTML it should behave the same as if an html syntax directive comment were present. It seems like these assumptions will benefit a lot of users (myself included).

4. Purging scopes for non-intrinsic identifiers. I’ve always hated these and only originally included a few because it seemed expected. They add just a touch of pointless chaos, since a short list is arbitrary and a more complete list causes false positives when you’re not in the env where those are really globals. Even with the short list I’ve seen that a bunch.

5. Remove array/generator comprehensions support. This feature was abandoned before ES2015 was completed, supplanted by other solutions.

6. Corrections: Reflect was in the intrinsic constructor list instead of the intrinsic namespace list; excelsior would fail to color braces on async arrow functions correctly.

### CODE REVIEW

**Comment by blake-regalia** [comment]
> but I’m unsure how to get the build stuff working and I assume that needs to be run before this can be committed to master

I'll take care of this now.

> I’ve added handling of template tags named exactly 'css' or 'html' when no directive comment is present.

This seems reasonable, although i'm worried about intruding on user's tag variable names for syntaxes in general. I've been thinking about adding a key binding to make syntax annotation much more accessible, i.e., to automatically insert ```/* syntax: $1 */ `$string` ``` where `$1` is where the cursor gets placed after the key binding and `$string` being the next tab stop. The idea is to make it only a few keystrokes whether the cursor is inside an existing template literal or getting ready to insert a new one.

> it uses the custom CSS rules rather than deferring to sublime css, which has more issues with interpolation & a brace matching bug with nested vars that drives me insane (shown not happening in the screenie above)

Is this affecting the current nested CSS syntax? Would you be able to provide an example so I can check it out to see if I can fix that too?

> Purging scopes for non-intrinsic identifiers. I’ve always hated these and only originally included a few because it seemed expected. They add just a touch of pointless chaos

👏  same here

**Comment by blake-regalia** [comment]
The `css` and `html` tag rules are causing a build error at the moment since they rely on the `syntax_EXIT` context, which is not accessible from the generated `source.es.nested` syntax definition when they get copied there (the syntax that gets loaded for es code *within* template literals for nested es, e.g., `/* syntax: js */ `$NESTED_ES`). I will have to add some code to the generator to blacklist these rules or figure something else out. In the meantime, i'm disabling these so that we can get the rest of the changes thru.

**Comment by bathos** [comment]
> This seems reasonable, although i'm worried about intruding on user's tag variable names for syntaxes in general.

Yep, philosophically it’s off-flavor. In practice, I think the hypothetical collisions are a bit _too_ hypothetical to block the practical benefit. A name like 'dot' might collide, but at least personally if I named a template tag for sql 'html' and my editor decided to highlight the template as html, I would probably stop drinking for the night rather than open an issue :) In particular with the rise of lit-html (godspeed!), `css` and `html` tags seem like they should work out of the box in the same way JSX does.

That said, I think this is another scenario where compiling the sublime syntax def from some more-meta source could help, especially if there were some way that we could let users configure the specifics and _generate the customized def_ on their end. Maybe too crazy? But I’m definitely feeling the spaghetti-ness of the def anyway, so it might be time to explore new approaches soon.

> Is this affecting the current nested CSS syntax?

Yes. It’s not a major thing really, but `var(--x, var(--y))` reproduces it — the nested vars get misscoped. AFAIK, it’s not an issue with our usage; it’s in the default sublime CSS def. (And I should prob just open an issue there...). The simplified CSS def originally used for StyledJSX has another advantage for templates though, too, which is that it doesn’t bork if the string isn’t a stylesheet production (so query selectors for `querySelector`, media queries for `MediaQueryList`, etc play nice with it).

**Comment by blake-regalia** [comment]
re: `css`/`html` tags -- I figured out a nice way to make this compatible, will push another commit shortly.

**Comment by bathos** [comment]
awesome, thanks (as usual!)

**Pull request merged**
